//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project13_web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        public int Book_Id { get; set; }
        [Display(Name="ชื่อหนังสือ ")]
        public string Book_Name { get; set; }
        [Display(Name = "หมวดหมู่ ")]
        public string Category { get; set; }
        [Display(Name = "เรื่องสั้น ")]
        public string Short_Story { get; set; }
        [Display(Name = "ผู้เขียน ")]
        public string Author { get; set; }
        [Display(Name = "สำนักพิมพ์ ")]
        public string Publisher { get; set; }
        [Display(Name = "ราคา ")]
        public Nullable<decimal> Price { get; set; }
        [Display(Name = "รูปหนังสือ ")]
        public string Image { get; set; }
    }
}
