//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project13_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_Id { get; set; }
        public string userEmail { get; set; }
        public Nullable<int> book_id { get; set; }
        public string Book_Name { get; set; }
        public string Book_Cat { get; set; }
        public Nullable<int> quanity { get; set; }
        public Nullable<decimal> total { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string pay_select { get; set; }
    }
}
